name: open-rdma-driver CI test
on:
  pull_request:
    branches: [ci]
  push:
    branches: [ci]

jobs:
  ci-check:
    name: CI test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: datenlord/blue-rdma
          ref: next
          fetch-depth: 1
          path: blue-rdma
      - name: build and simulate
        run : |
          ./blue-rdma/setup.sh
          ./blue-rdma/run_one.sh
      - name: run cargo build
        run : cargo build --verbose
      - name: run cargo test
        run : cargo test --verbose
      